<?php
/**
 * Tamil-Catholic-Lectionary 1.0
 * Formats the day code to name for the day
 * @author Br. Jayarathina Madharasan SDR
 */
use Medoo\Medoo;

/**
 * Set the feast day names in Tamil.
 *
 * @author Br. Jayarathina Madharasan SDR
 *        
 */
class TamilLectionaryFeastNameFramer {
	
	/**
	 * Recieves RomanCalendarYear object and returns it with tamil feast name set.
	 *
	 * @param RomanCalendarYear $rcy
	 * @return RomanCalendarYear
	 */
	public static function setName(RomanCalendarYear $rcy) {
		foreach ( $rcy->fullYear as $month => $value ) { // Loop through each month
			foreach ( $value as $days => $feasts ) { // Loop through each day
				foreach ( $feasts as $feastNum => $feast ) { // Loop through each events in the day
					$rcy->fullYear [$month] [$days] [$feastNum] ['ta_name'] = TamilLectionaryFeastNameFramer::getSingleTitle ( $feast ['code'], $rcy->calcConfig ['feastSettings'] ['EPIPHANY_ON_A_SUNDAY'], $rcy->calcConfig ['calendars'] );
				}
			}
		}
		return $rcy;
	}
	
	/**
	 * For Weekday codes, names are set.
	 * That is day codes are converted to full names.
	 * For feasts, names are taken from the database.
	 *
	 * @param string $dayCode
	 *        	- As generated by RomanCalendar Library. It will be a unique identifier for that feast.
	 *        	For a ferial days (with no feast) a code is generated in the following syntax: `<SEASON CODE><WEEK NUMBER>-<DAY NUMBER><DAY NAME>`.
	 *        	
	 * @param boolean $isEpiphanySunday
	 *        	- Is Epiphany celebrated on a Sunday
	 * @param array $calList
	 *        	- List of local calendars
	 * @return string - the feast name in tamil
	 */
	public static function getSingleTitle($dayCode, $isEpiphanySunday, $calList) {
		
		// Exceptions
		$RomanCalendarDayException = array (
				'CW02-0Sun' => 'கிறிஸ்து பிறப்பு விழாவுக்குப் பின் 2ம் ஞாயிறு',
				'CW03-Epiphany' => 'ஆண்டவரின் திருக்காட்சி',
				'CW04-Baptism' => 'ஆண்டவரின் திருமுழுக்கு',
				'CW01-HolyFamily' => 'இயேசு, மரியா, யோசேப்பின் திருக்குடும்பம்',
				
				'LW00-3Wed' => 'திருநீற்றுப் புதன்',
				'LW06-0Sun' => 'ஆண்டவருடைய திருப்பாடுகளின் குருத்து ஞாயிறு',
				'LW06-4Thu' => 'ஆண்டவரின் இராவுணவுத் திருப்பலி',
				'LW06-5Fri' => 'திருப்பாடுகளின் வெள்ளி',
				'LW06-6Sat' => 'பாஸ்கா  திருவிழிப்பு',
				
				'EW01-0Sun' => 'ஆண்டவருடைய உயிர்ப்பின் பாஸ்கா ஞாயிறு',
				'EW07-Ascension' => 'ஆண்டவரின் விண்ணேற்றம்',
				'EW08-Pentecost' => 'தூய ஆவி ஞாயிறு',
				
				'OW00-Trinity' => 'மூவொரு கடவுள்',
				'OW00-CorpusChristi' => 'கிறிஸ்துவின் திருவுடல், திருஇரத்தம்',
				'OW00-SacredHeart' => 'இயேசுவின் திருஇதயம்',
				'OW00-ImmaculateHeart' => 'தூய கன்னி மரியாவின் மாசற்ற இதயம்',
				'OW00-MaryMotherofChurch' => 'தூய கன்னி மரியா திரு அவையின் அன்னை',
				
				'OW34-0Sun' => 'இயேசு கிறிஸ்து அனைத்துலக அரசர்' 
		);
		
		if (isset ( $RomanCalendarDayException [$dayCode] ))
			return $RomanCalendarDayException [$dayCode];
		
		// Calculating for ferial days.
		$feastTitle = '';
		
		$wkNo = intval ( substr ( $dayCode, 2, 2 ) ); // Get the week number
		$wkDay = substr ( $dayCode, - 4, 1 ); // Get Day
		
		switch (substr ( $dayCode, 0, 2 )) {
			case 'AW' : // Advent
				if ($wkNo == 5)
					$feastTitle = 'திருவருகைக் கால வார நாள்கள் - டிசம்பர் ' . substr ( $dayCode, - 2 );
				else
					$feastTitle = 'திருவருகைக்காலம் ' . $wkNo . 'ஆம் வாரம் - ' . TamilLectionaryUtil::$tamilDayFull [$wkDay];
				break;
			case 'CW' : // Christmas
				switch ($wkNo) {
					case 1 : // Christmas Octave
						$feastTitle = ' கிறிஸ்து பிறப்பின் எண்கிழமையில் ' . intval ( substr ( $dayCode, - 2 ) - 24 ) . 'ஆம் நாள் - டிசம்பர் ' . substr ( $dayCode, - 2 );
						break;
					case 2 : // Before Epiphany
						$feastTitle = 'சனவரி ' . substr ( $dayCode, - 1 );
						break;
					case 3 : // After Epiphany
						if ($isEpiphanySunday) {
							$feastTitle = 'திருக்காட்சி விழாவுக்குப் பின் ' . TamilLectionaryUtil::$tamilDayFull [substr ( $dayCode, - 1 )];
						} else {
							$feastTitle = 'சனவரி ' . (6 + substr ( $dayCode, - 1 ));
						}
						break;
				}
				break;
			case 'LW' : // Lent
				switch ($wkNo) {
					case 0 :
						$feastTitle = 'திருநீற்றுப் புதனுக்குப் பின் வரும் ' . TamilLectionaryUtil::$tamilDayFull [$wkDay];
						break;
					case 6 :
						$feastTitle = 'புனித வாரம் - ' . TamilLectionaryUtil::$tamilDayFull [$wkDay];
						break;
					default :
						$feastTitle = 'தவக்காலம் ' . $wkNo . 'ஆம் வாரம் - ' . TamilLectionaryUtil::$tamilDayFull [$wkDay];
						break;
				}
				break;
			case 'EW' : // Easter
				if ($wkNo == 1)
					$feastTitle = 'பாஸ்கா எண்கிழமை - ' . TamilLectionaryUtil::$tamilDayFull [$wkDay];
				else
					$feastTitle = 'பாஸ்கா ' . $wkNo . 'ஆம் வாரம் - ' . TamilLectionaryUtil::$tamilDayFull [$wkDay];
				break;
			case 'OW' :
				$feastTitle = 'பொதுக்காலம் ' . $wkNo . 'ஆம் வாரம் - ' . TamilLectionaryUtil::$tamilDayFull [$wkDay];
				break;
		}
		
		$feastTitle = str_replace ( ' 1ஆம்', ' முதல்', $feastTitle );
		
		/*
		 * If $feastTitle is still not set then it is not a ferial day, but rather solemnity, feast or a memory.
		 * Hence the name of the saint is to be taken from database
		 */
		
		if (empty ( $feastTitle )) {
			$database = new Medoo ( array (
					'database_type' => DB_TYPE,
					'server' => DB_HOST,
					'charset' => DB_CHARSET,
					'username' => DB_USER,
					'password' => DB_PASSWORD,
					'database_name' => DB_NAME 
			) );
			// Loop through all calendars
			foreach ( $calList as $calName ) {
				$res = $database->get ( 'general' . $calName, 'feast_ta', array (
						'feast_code' => $dayCode 
				) );
				if (! empty ( $res )) {
					$feastTitle = ( string ) $res;
					break;
				}
			}
		}
		
		if (! $feastTitle) // should never happen
			die ( "ERROR: Name for code: $dayCode not in database" );
		return $feastTitle;
	}
}